export interface DailyTopic {
  dayOfWeek: number;
  dayName: string;
  title: string;
  subtitle: string;
  emoji: string;
  color: string;
  questions: string[];
}

export const DAILY_TOPICS: DailyTopic[] = [
  {
    dayOfWeek: 0, dayName: 'Sunday',
    title: 'Love Languages & Emotional Connection',
    subtitle: 'Understanding how we give and receive love',
    emoji: '💗',
    color: 'linear-gradient(135deg, #f43f5e 0%, #be185d 100%)',
    questions: [
      'What is your primary love language, and has it changed since we started dating?',
      'Describe a specific moment when you felt most deeply loved by me.',
      'What small, everyday act of mine makes you feel the most seen and cared for?',
      'Is there a way I express love that doesn\'t land the way I intend it to?',
      'What does emotional intimacy feel like to you?',
      'What rituals or routines help you feel most connected to me daily?',
      'When do you feel emotionally safest with me?',
      'Is there something you need from me emotionally that you haven\'t asked for yet?',
      'How do you feel love differently when stressed versus when things are calm?',
      'What does it mean to you to be truly known by a partner?',
    ],
  },
  {
    dayOfWeek: 1, dayName: 'Monday',
    title: 'Trust & Vulnerability',
    subtitle: 'Being fully known and fully safe',
    emoji: '🔐',
    color: 'linear-gradient(135deg, #111827 0%, #000000 100%)',
    questions: [
      'What does trust mean to you at its deepest level?',
      'What\'s one fear about being fully known that you still carry?',
      'Describe a past experience that shaped your ability to trust in relationships.',
      'Has there been a moment in our relationship when your trust wavered?',
      'What would I need to do to make you feel more emotionally safe?',
      'Is there a part of yourself you still hide because you\'re afraid of my response?',
      'What makes you feel truly secure in our relationship?',
      'How do you know when you can fully trust someone?',
      'What does being vulnerable look like for you?',
      'What\'s something you\'ve never told anyone that you could tell me?',
    ],
  },
  {
    dayOfWeek: 2, dayName: 'Tuesday',
    title: 'Dreams & Future',
    subtitle: 'Where we are going together',
    emoji: '🌟',
    color: 'linear-gradient(135deg, #7c3aed 0%, #4f46e5 100%)',
    questions: [
      'Where do you see us in 5 years?',
      'What is one dream you have for us that you\'ve never fully shared?',
      'What kind of home do you want us to build together?',
      'What traditions do you want us to create as a couple?',
      'What adventure is on your bucket list that you want to do with me?',
      'What legacy do you want us to leave together?',
      'What does your ideal daily life with me look like in 10 years?',
      'What goal do you most want us to achieve together this year?',
      'How do you want to grow as a person, and how can I support that?',
      'What does your dream life actually look like?',
    ],
  },
  {
    dayOfWeek: 3, dayName: 'Wednesday',
    title: 'Gratitude & Appreciation',
    subtitle: 'What we love and cherish about each other',
    emoji: '💛',
    color: 'linear-gradient(135deg, #f59e0b 0%, #d97706 100%)',
    questions: [
      'What is one thing I do that always makes you smile?',
      'What have I done recently that meant a lot to you?',
      'What do you appreciate about me that you haven\'t said lately?',
      'What do you love about the way I treat you?',
      'What is something you\'re proud of me for?',
      'How has my support helped you grow?',
      'What quality of mine do you wish you had?',
      'What do I do that makes you feel truly loved?',
      'What small thing I do makes the biggest difference?',
      'What is your favorite thing about us as a team?',
    ],
  },
  {
    dayOfWeek: 4, dayName: 'Thursday',
    title: 'Growth & Communication',
    subtitle: 'Getting better together',
    emoji: '🌱',
    color: 'linear-gradient(135deg, #059669 0%, #047857 100%)',
    questions: [
      'What is one area you feel we could communicate better in?',
      'What have we overcome together that made us stronger?',
      'What is something you wish I understood better about you?',
      'How can I be a better partner to you?',
      'What habit would you like us to build together?',
      'What does your ideal conflict resolution look like?',
      'Is there something I do that unintentionally hurts you?',
      'What makes you feel most heard in a conversation?',
      'What does growth look like for you in this relationship?',
      'What is one thing you\'ve learned from us being together?',
    ],
  },
  {
    dayOfWeek: 5, dayName: 'Friday',
    title: 'Fun & Memories',
    subtitle: 'Laughing and living our best moments',
    emoji: '🎉',
    color: 'linear-gradient(135deg, #ec4899 0%, #be185d 100%)',
    questions: [
      'What is your favorite memory of us so far?',
      'What is the funniest thing I have ever said or done?',
      'What is our best inside joke?',
      'What would our reality TV show be called?',
      'What was your reaction the first time you realized you liked me?',
      'What is the most fun we have ever had together?',
      'What is a place you want us to visit together?',
      'What would our signature couple dance move be?',
      'What is your favorite photo of us and why?',
      'If we were in a movie, what genre would it be?',
    ],
  },
  {
    dayOfWeek: 6, dayName: 'Saturday',
    title: 'Intimacy & Closeness',
    subtitle: 'Being truly close',
    emoji: '🥰',
    color: 'linear-gradient(135deg, #f43f5e 0%, #7c3aed 100%)',
    questions: [
      'When do you feel closest to me?',
      'What is something you love about our physical connection?',
      'What makes you feel most attractive or confident around me?',
      'What is your favorite way we spend quality time together?',
      'What is a moment of closeness between us you never want to forget?',
      'How do you feel about how we balance time together and time apart?',
      'What does being in love feel like to you right now?',
      'What do you want more of in our relationship?',
      'What makes you choose me every day?',
      'What is the most loving thing I could do for you this week?',
    ],
  },
];
