export const TRUTH_PROMPTS = [
  'What is the most embarrassing thing you have done in front of me?',
  'What do you secretly wish I would do more often?',
  'What is your biggest insecurity in our relationship?',
  'Have you ever lied to me? What was it about?',
  'What is one thing you wish I understood better about you?',
  'What is your favourite memory of us so far?',
  'What is something you have never told anyone?',
  'What first attracted you to me?',
  'What is your biggest fear about our future together?',
  'What is one habit of mine you wish I would change?',
  'How do you really feel when we argue?',
  'What is the most romantic thing you have ever imagined for us?',
  'What makes you feel most loved by me?',
  'Is there something you have always wanted to ask me but never did?',
  'What is your love language and do I fulfil it?',
];

export const DARE_PROMPTS = [
  'Send me the most embarrassing photo in your camera roll right now.',
  'Record a 10-second voice note telling me something sweet.',
  'Tell me your honest first impression of me when we first met.',
  'Write me a 3-line poem right now.',
  'Screenshot your most-used emoji and explain why.',
  'Describe our relationship using only song titles.',
  'Tell me one thing you have been too shy to say.',
  'List 5 things you love about me in 60 seconds.',
  'Recreate your reaction when you first realised you liked me.',
  'Say something in another language and tell me what it means.',
  'Share your most recent Google search.',
  'Tell me your honest opinion about our first date.',
  'Give me a compliment you have never given before.',
  'Describe what our future home looks like in your imagination.',
  'Tell me one dream you have that you have never shared.',
];

export const THIS_OR_THAT: Array<{ this: string; that: string }> = [
  { this: 'Morning person ☀️', that: 'Night owl 🌙' },
  { this: 'Beach 🏖️', that: 'Mountains ⛰️' },
  { this: 'Stay in 🛋️', that: 'Go out 🎉' },
  { this: 'Texting 💬', that: 'Calling 📞' },
  { this: 'Sweet 🍫', that: 'Salty 🍟' },
  { this: 'Dogs 🐶', that: 'Cats 🐱' },
  { this: 'Movie night 🎬', that: 'Game night 🎮' },
  { this: 'Cook at home 🍳', that: 'Eat out 🍽️' },
  { this: 'Winter ❄️', that: 'Summer ☀️' },
  { this: 'Road trip 🚗', that: 'Fly ✈️' },
  { this: 'Romantic dinner 🕯️', that: 'Surprise picnic 🧺' },
  { this: 'Big wedding 💒', that: 'Small wedding 💍' },
  { this: 'City life 🏙️', that: 'Countryside 🌿' },
  { this: 'Early bird 🐦', that: 'Snooze button 😴' },
  { this: 'Read books 📚', that: 'Watch series 📺' },
  { this: 'Breakfast in bed 🥐', that: 'Breakfast out ☕' },
  { this: 'Dancing 💃', that: 'Karaoke 🎤' },
  { this: 'Save money 💰', that: 'Spend on experiences 🎡' },
  { this: 'Gym 💪', that: 'Outdoor walks 🌳' },
  { this: 'Pizza 🍕', that: 'Jollof rice 🍛' },
];

export const NEVER_HAVE_I_EVER = [
  'Never have I ever stayed up all night talking to someone I like.',
  'Never have I ever sent a message to the wrong person.',
  'Never have I ever cried at a movie.',
  'Never have I ever had a secret crush on a friend.',
  'Never have I ever lied to get out of plans.',
  'Never have I ever stalked an ex on social media.',
  'Never have I ever fallen asleep on a date.',
  'Never have I ever said "I love you" first.',
  'Never have I ever forgotten an important anniversary.',
  'Never have I ever pretended to be sick to avoid going out.',
  'Never have I ever danced in public alone.',
  'Never have I ever kept a gift I should have returned.',
  'Never have I ever read someone else\'s private messages.',
  'Never have I ever been caught staring at someone.',
  'Never have I ever laughed at the wrong moment.',
  'Never have I ever cried because I missed someone too much.',
  'Never have I ever written a love letter.',
  'Never have I ever been so nervous I forgot what I was saying.',
  'Never have I ever planned something romantic that went wrong.',
  'Never have I ever fallen asleep while on the phone with someone.',
];

export const WOULD_YOU_RATHER: Array<{ a: string; b: string }> = [
  { a: 'Be able to fly ✈️', b: 'Be invisible 👻' },
  { a: 'Live in the past ⏮️', b: 'Live in the future ⏭️' },
  { a: 'Be famous 🌟', b: 'Be incredibly rich 💰' },
  { a: 'Have more money 💵', b: 'Have more time ⏳' },
  { a: 'Only eat sweet food 🍰', b: 'Only eat savoury food 🥩' },
  { a: 'Always know the truth 🔮', b: 'Stay blissfully unaware 😊' },
  { a: 'Lose all your memories 🧊', b: 'Never make new memories 😶' },
  { a: 'Travel everywhere solo 🌍', b: 'Stay home with loved ones 🏠' },
  { a: 'No phone for a year 📵', b: 'No internet for a year 🚫' },
  { a: 'Always be too hot 🥵', b: 'Always be too cold 🥶' },
  { a: 'Never sleep again 😳', b: 'Never eat again 🍽️' },
  { a: 'Read minds 🧠', b: 'See the future 🔮' },
  { a: 'Give up social media 📱', b: 'Give up music 🎵' },
  { a: 'Be incredibly smart 🎓', b: 'Be incredibly attractive 💅' },
  { a: 'Speak every language 🗣️', b: 'Play every instrument 🎸' },
  { a: 'Have a rewind button ⏪', b: 'Have a fast-forward button ⏩' },
  { a: 'Always be 10 min late ⏰', b: 'Always be 20 min early 🕐' },
  { a: 'Live by the ocean 🌊', b: 'Live in the mountains ⛰️' },
  { a: 'Have no regrets 😌', b: 'Learn from every mistake 📚' },
  { a: 'Stay with your partner forever 💑', b: 'Travel the world solo 🌏' },
];

export const OPEN_QUESTIONS: string[] = [
  'What is your dream vacation?',
  'What is your go-to comfort food?',
  'What would you do if you won the lottery tomorrow?',
  'What is something you have always wanted to learn?',
  'Describe your perfect lazy Sunday.',
  'What is one thing that always makes you smile?',
  'What is your biggest dream in life right now?',
  'What does your ideal home look like?',
  'What is one thing you wish people understood about you?',
  'What memory from your childhood do you cherish most?',
  'What is something you are secretly proud of?',
  'What would your perfect birthday look like?',
  'What is the best gift anyone has ever given you?',
  'What song is stuck in your head most often?',
  'What superpower would you pick and why?',
  'What is one habit you want to build this year?',
  'What does love mean to you in one sentence?',
  'What is your favourite way to spend a Friday night?',
  'If you could meet anyone in history, who and why?',
  'What is something that always cheers you up when you are down?',
];

export const PICK_A_NUMBER_QUESTIONS: Array<{ number: number; category: string; question: string }> = [
  { number: 1, category: 'Romantic', question: 'What is your favourite memory of us?' },
  { number: 2, category: 'Romantic', question: 'When did you first realise you were falling for me?' },
  { number: 3, category: 'Romantic', question: 'What is the most romantic thing I have ever done for you?' },
  { number: 4, category: 'Romantic', question: 'Describe our perfect day together.' },
  { number: 5, category: 'Romantic', question: 'What is your favourite way I show you love?' },
  { number: 6, category: 'Romantic', question: 'What part of our love story would you relive forever?' },
  { number: 7, category: 'Romantic', question: 'What song reminds you of me and why?' },
  { number: 8, category: 'Romantic', question: 'What do you love most about our relationship?' },
  { number: 9, category: 'Romantic', question: 'How has being with me changed your life?' },
  { number: 10, category: 'Romantic', question: 'What is your favourite moment between us this month?' },
  { number: 11, category: 'Deep', question: 'What does love mean to you?' },
  { number: 12, category: 'Deep', question: 'What is your biggest fear and how can I help?' },
  { number: 13, category: 'Deep', question: 'What is one thing you wish we talked about more?' },
  { number: 14, category: 'Deep', question: 'What does home feel like to you?' },
  { number: 15, category: 'Deep', question: 'What is the most important lesson love has taught you?' },
  { number: 16, category: 'Deep', question: 'How do you define happiness?' },
  { number: 17, category: 'Deep', question: 'What is something you want to experience before you die?' },
  { number: 18, category: 'Deep', question: 'What would you tell your younger self about love?' },
  { number: 19, category: 'Deep', question: 'What is your love language and how can I serve it better?' },
  { number: 20, category: 'Deep', question: 'What are you most grateful for in your life right now?' },
  { number: 21, category: 'Appreciation', question: 'What is one thing I do that always makes you smile?' },
  { number: 22, category: 'Appreciation', question: 'What is something I did this week that meant a lot to you?' },
  { number: 23, category: 'Appreciation', question: 'What do you appreciate about me that you have not said lately?' },
  { number: 24, category: 'Appreciation', question: 'What do you love about the way I treat you?' },
  { number: 25, category: 'Appreciation', question: 'What is something you are proud of me for?' },
  { number: 26, category: 'Appreciation', question: 'How has my support helped you grow?' },
  { number: 27, category: 'Appreciation', question: 'What is a quality of mine you wish you had?' },
  { number: 28, category: 'Appreciation', question: 'What do I do that makes you feel truly loved?' },
  { number: 29, category: 'Appreciation', question: 'What small thing I do makes the biggest difference?' },
  { number: 30, category: 'Appreciation', question: 'What is your favourite thing about us as a team?' },
  { number: 31, category: 'Future', question: 'Where do you see us in 5 years?' },
  { number: 32, category: 'Future', question: 'What future adventure should we plan together?' },
  { number: 33, category: 'Future', question: 'What kind of home do you want us to build?' },
  { number: 34, category: 'Future', question: 'What traditions do you want us to create?' },
  { number: 35, category: 'Future', question: 'What is one goal you want us to achieve together this year?' },
  { number: 36, category: 'Future', question: 'What place in the world do you most want to visit with me?' },
  { number: 37, category: 'Future', question: 'What legacy do you want us to leave together?' },
  { number: 38, category: 'Future', question: 'How many children do you see us having?' },
  { number: 39, category: 'Funny', question: 'What would our reality TV show be called?' },
  { number: 40, category: 'Funny', question: 'What is my most embarrassing habit?' },
  { number: 41, category: 'Funny', question: 'If I were an animal, what would I be?' },
  { number: 42, category: 'Funny', question: 'What is the funniest thing I have ever said?' },
  { number: 43, category: 'Funny', question: 'What would our signature couple dance move be?' },
  { number: 44, category: 'Funny', question: 'If we had a theme song, what would it be?' },
  { number: 45, category: 'Growth', question: 'What is one area we could communicate better?' },
  { number: 46, category: 'Growth', question: 'What have we overcome together that made us stronger?' },
  { number: 47, category: 'Growth', question: 'What is one thing you wish I understood better about you?' },
  { number: 48, category: 'Growth', question: 'How can I be a better partner to you?' },
  { number: 49, category: 'Growth', question: 'What habit would you like us to build together?' },
  { number: 50, category: 'Growth', question: 'What does your ideal conflict resolution look like?' },
];
