export const TRUTH_PROMPTS = [
  'What is the most embarrassing thing you have done in front of me?',
  'What do you secretly wish I would do more often?',
  'What is your biggest insecurity in our relationship?',
  'Have you ever lied to me? What was it about?',
  'What is one thing you wish I understood better about you?',
  'What is your favourite memory of us so far?',
  'What is something you have never told anyone?',
  'What first attracted you to me?',
  'What is your biggest fear about our future together?',
  'What is one habit of mine you wish I would change?',
  'How do you really feel when we argue?',
  'What is the most romantic thing you have ever imagined for us?',
  'What makes you feel most loved by me?',
  'Is there something you have always wanted to ask me but never did?',
  'What is your love language and do I fulfil it?',
];

export const DARE_PROMPTS = [
  'Send me the most embarrassing photo in your camera roll right now.',
  'Record a 10-second voice note telling me something sweet.',
  'Tell me your honest first impression of me when we first met.',
  'Write me a 3-line poem right now.',
  'Screenshot your most-used emoji and explain why.',
  'Describe our relationship using only song titles.',
  'Tell me one thing you have been too shy to say.',
  'List 5 things you love about me in 60 seconds.',
  'Recreate your reaction when you first realised you liked me.',
  'Say something in another language and tell me what it means.',
  'Share your most recent Google search.',
  'Tell me your honest opinion about our first date.',
  'Give me a compliment you have never given before.',
  'Describe what our future home looks like in your imagination.',
  'Tell me one dream you have that you have never shared.',
];

export const THIS_OR_THAT: Array<{ this: string; that: string }> = [
  { this: 'Morning person ☀️', that: 'Night owl 🌙' },
  { this: 'Beach 🏖️', that: 'Mountains ⛰️' },
  { this: 'Stay in 🛋️', that: 'Go out 🎉' },
  { this: 'Texting 💬', that: 'Calling 📞' },
  { this: 'Sweet 🍫', that: 'Salty 🍟' },
  { this: 'Dogs 🐶', that: 'Cats 🐱' },
  { this: 'Movie night 🎬', that: 'Game night 🎮' },
  { this: 'Cook at home 🍳', that: 'Eat out 🍽️' },
  { this: 'Winter ❄️', that: 'Summer ☀️' },
  { this: 'Road trip 🚗', that: 'Fly ✈️' },
  { this: 'Romantic dinner 🕯️', that: 'Surprise picnic 🧺' },
  { this: 'Big wedding 💒', that: 'Small wedding 💍' },
  { this: 'City life 🏙️', that: 'Countryside 🌿' },
  { this: 'Early bird 🐦', that: 'Snooze button 😴' },
  { this: 'Read books 📚', that: 'Watch series 📺' },
  { this: 'Breakfast in bed 🥐', that: 'Breakfast out ☕' },
  { this: 'Dancing 💃', that: 'Karaoke 🎤' },
  { this: 'Save money 💰', that: 'Spend on experiences 🎡' },
  { this: 'Gym 💪', that: 'Outdoor walks 🌳' },
  { this: 'Pizza 🍕', that: 'Jollof rice 🍛' },
];

export const NEVER_HAVE_I_EVER = [
  'Never have I ever stayed up all night talking to someone I like.',
  'Never have I ever sent a message to the wrong person.',
  'Never have I ever cried at a movie.',
  'Never have I ever had a secret crush on a friend.',
  'Never have I ever lied to get out of plans.',
  'Never have I ever stalked an ex on social media.',
  'Never have I ever fallen asleep on a date.',
  'Never have I ever said "I love you" first.',
  'Never have I ever forgotten an important anniversary.',
  'Never have I ever pretended to be sick to avoid going out.',
  'Never have I ever danced in public alone.',
  'Never have I ever kept a gift I should have returned.',
  'Never have I ever read someone else\'s private messages.',
  'Never have I ever been caught staring at someone.',
  'Never have I ever laughed at the wrong moment.',
  'Never have I ever cried because I missed someone too much.',
  'Never have I ever written a love letter.',
  'Never have I ever been so nervous I forgot what I was saying.',
  'Never have I ever planned something romantic that went wrong.',
  'Never have I ever fallen asleep while on the phone with someone.',
];
